### ISSUE TITLE
Rounded Corners

### ISSUE THREAD

**Issue by shrivatsasomany** [farshadjahanmanesh/loady#4]
Hey!

Unlike your examples, my button doesn't have rounded edges.

```button.layer.cornerRadius```

doesn't work either. How can I round the corners?

**Comment by farshadjahanmanesh** [comment]
hi, it's weird 
try adding **layer.cornerRadius** inside user defined in storyboard
<img width="272" alt="Screen Shot 2019-06-21 at 1 51 51 AM" src="https://user-images.githubusercontent.com/13612410/59882321-26c91c80-93c7-11e9-9382-9a3af876a6f2.png">

but adding 
`button.layer.cornerRadius` 
in code should be ok, check and see maybe you are changing the layer corner from somewhere else, because I tested it just now and everything was fine.
 feel free to continue this thread

**Comment by shrivatsasomany** [comment]
Hey! 

Adding it to the runtime attributes did the trick, setting the cornerRadius in the viewController didn't work however. 

Thanks!
